GET http://localhost:8080/api/rest/group

###

GET http://localhost:8080/api/rest/group?query=title%20%3D%3D%20%27dfdfs%27

###

GET http://localhost:8080/api/rest/group/grp002

###

POST http://localhost:8080/api/rest/group/
Content-Type: application/json

{
  "id": "grp0090978",
  "title": "4",
  "description": "4"
}

###

PUT http://localhost:8080/api/rest/group/grp002
Content-Type: application/json

{
  "id": "grp002",
  "title": "dfsdsdfs",
  "description": "dfsfdm"
}

###

DELETE http://localhost:8080/api/rest/group/grp0090978

###

GET http://localhost:8080/api/rest/group/grp002/item

###

GET http://localhost:8080/api/rest/group/grp002/item/item1

###

POST http://localhost:8080/api/rest/group/grp002/item
Content-Type: application/json

{
  "id": "item3"
}

###
